
title: Postmodernism is bad for your health
# email: diegoalvarado26@hotmail.com

description: My thoughts on stuff
url: "https://diegoalvarado26.github.io"
baseurl: "/blog"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# author:
#   name: Diego Alvarado
#   email: dmalvaradog26@gmail.com

github_username: diegoalvarado26

author: Diego Alvarado
email : dmalvaradog26@gmail.com
markdown: kramdown

twitter:
    username: diego_alv26
    card: summary

theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
        twitter: diego_alv26
        github: diegoalvarado26
        instagram: diegoalvarado.26

plugins:
 - jekyll-feed
 - jekyll-seo-tag
